### ISSUE TITLE
Make zipRadius() robust against cases where there isn't 1 correct zip code

### ISSUE THREAD

**Issue by richierocks** [EAVWing/ZipRadius#2]
Currently `zipRadius()` has unexpected behavior for the case when `zipcode` has length greater than one. In the following case, two zip codes are passed, and the return value only includes rows for the second value (with no warning).

```r
library(ZipRadius)
zipRadius(c("99501", "90210"), 1)
##     zip          city state latitude longitude Distance
## 1 90210 Beverly Hills    CA 34.08881 -118.4061        0
```

It may be possible to vectorize `zipRadius()`, but the simplest fix is just to check that `zipcode` is a character vector of length one. There are lots of ways to do this; my favorite is to add this line to the start of the function.

```r
assertive.types::assert_is_a_string(zipcode)
```

----

Another problem is that if the zip code doesn't exist, there is an unclear error message. Here, 

```r
library(ZipRadius)
zipRadius("99999", 1)
## Error in data.frame(..., check.names = FALSE) : 
##   arguments imply differing number of rows: 44336, 0
```

You can fix this by checking that `refPoint` contains a value. Something like

```r
if(length(refPoint) == 0) {
  stop("The zipcode you specified wasn't found")
}
```

I'm not sure if you want to throw an error or to throw a warning and return an empty data frame.

**Comment by EAVWing** [comment]
looks good, thanks Richie
